### ISSUE TITLE
bootstraps version when evaluating

### ISSUE THREAD

**Issue by jingweiz** [Kaixhin/Atari#3]
Hi Kaixhin,
it's a really amazing repo here what you did, it's really great work!

One small problem here:
`opt.bootstraps > 0` and when in evaluation mode, in Agent.lua line 175:
`aIndex = torch.mode(QHeadsMaxInds)`

Here, when running on gpu, QHeadsMaxInds is a cudaTensor, but "mode" is not implemented in cutorch, so this line might be changed to:
`aIndex = torch.mode(QHeadsMaxInds:reshape(QHeadsMaxInds:size()[1]):float())[1]`

Can you maybe look into this issue?
Also any plan on adding on this paper: [Asynchronous Methods for Deep Reinforcement Learning](http://arxiv.org/pdf/1602.01783v1.pdf) ? :)

**Comment by Kaixhin** [comment]
Thanks, but I still haven't managed to replicate DeepMind's results, so if you spot any other errors please let me know.

Somehow missed that one - have just pushed a fix by casting it to float. Ran a quick test and seems to be fine. Any reason for reshaping before casting?

I would love to work on an open source implementation of A3C but a) Lua doesn't support proper multithreading in the core language and b) a lot of multithreading libraries (in general) use locks, so I don't think it'll be that easy to do. So that's not making it into this repo any time soon.

**Comment by jingweiz** [comment]
Yeah how you fixed is fine.
As for the A3C paper, according to what you explained, I wonder if deepmind did it with lua or are they switching to tensorflow already.
By deepmind's results do you mean the nature one or the following ones?
And just out of curiosity, when you started this repo, why didn't you build on deepmind's original code but started from scratch?

**Comment by Kaixhin** [comment]
DeepMind use Torch a lot, and Theano (plus maybe wrappers) internally. Not sure if they've started using TensorFlow but it does seem the most appropriate system to build AlphaGo on. So no idea.

Nature and following. Unfortunately I don't currently have the resources to run several tests at once.

To make sure I understood the algorithms / to make cleaner, more modular code / to annoy myself as it gets harder to find mistakes in my code... Also, if people want to work on DQNs and they use this code then it'll be a lot easier to contact me than one of the original coders from DeepMind.
