### ISSUE TITLE
Can I convert rank-based prioritized experience replay to a python version

### ISSUE THREAD

**Issue by Damcy** [Kaixhin/Atari#49]
I want to implement the prioritized by python, and now I find your torch version and get inspired. 
So can I convert rank-based prioritized experience replay to a python version, maybe some place will refer to your code?

**Comment by Kaixhin** [comment]
Sure, go ahead - a reference to this repo would very much be appreciated :+1: 

Though bear in mind that I haven't managed to consistently replicate the results in the paper, and the code has changed since the last time I replicated the results on Frostbite, so bugs may have been introduced. I would suggest using this as a reference but trying to implement prioritised experience replay from the paper when you can. If you spot any discrepancies then please report back as it may be a bug with our code.

**Comment by Damcy** [comment]
Okay. Thanks.
