### ISSUE TITLE
Possible improvements on speeding up

### ISSUE THREAD

**Issue by YurongYou** [Kaixhin/Atari#54]
I found some possible speedup improvements which may speed the training time by some constant, list them as follows.
1. In `Atari/async/AC3Agent.lua:53`,
   
   ```
   local V, probability = table.unpack(self.policyNet_:forward(state))
   ```
   
   Maybe we can store the `V` and `probability` as we store the actions in `self.actions`, then in the gradient accumulating phrase, the redundant forwarding at line `87` can be avoided.
2. In `Atari/async/NstepQAgent.lua`, similar with 1, if we can store the Q values, we can avoid the redundant forwarding at line `81`.

A problem about logging is that if the running of async model suspends, although it can be resume from the save data, but the plotted statics graph will not include the previous scores. 

And by the way, I notice the comments at `AsyncMaster.lua:146-147`, I wonder maybe it's due to the serialization, as the `threads` package doc has addressed the problem. Maybe move the `require`s to the `torchSetup` will solve it.

**Comment by lake4790k** [comment]
@YurongYou  re 1 and 2: in the n step learning loop a `forward` must be done with the same inputs before doing the `backward` to set up the nets internal state, so it's not enough to cache the output of forward. One would also need to cache the internal state of the net for each forward as well and then reset it before backward, I'm not sure if this worths the hackiness.

re resuming in async: right, that can be improved

re the multi threaded instantiation of xitari: the crash happened in xitari code, not caused by serialization by `threads`.
